### ISSUE TITLE
Zeppelin saves 150MB in `/run`, crashing servers <2G RAM

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/layer-apache-bigtop-base#67] opened 2017-11-22 13:33 UTC
:flushed: 

For some reason, Zeppelin puts its entire webapp in `/run/zeppelin`, which consumes 150MB of space. Given that `/run` is max 10% of the RAM as defined by systemd, this crashes servers that have < 2GB of memory.

If this is wanted behavior, we should put a constraint on zeppelin in all the bundles, but I doubt this is what should happen?

**Comment by kwmonroe** [comment] 2018-08-07 22:04
Duped by https://github.com/juju-solutions/bigtop/issues/57.  Yes, you reported it first, and gave the root cause first, and gave failing scenarios first, but I happened to look at and answer the other one first ;)

The gist is that we should make zepp's war dir configurable, and probably default it to `/usr` or `/var` vs the pid dir. Closing this in favor of fixing in 57.

**Closed by kwmonroe** 2018-08-07 22:04 UTC
